# Cấu hình huấn luyện ResNet50 cho Action Classification

# Thư mục chứa kết quả train (weights, logs, visualizations)
output_dir: "/home/laptq/laptq-fs26-shoplifting-detection/runs/classification/fs26/v13.2dcnn.cluster-CNN-8--cut-l4+gen-hoangvt-thaovt-20260520"

resume_path: null # Path tới thư mục run để resume (nếu có)

# Thứ tự các class (Quan trọng: phải khớp với chỉ số khi lưu/load model)
classes:
  - "cho_tay_vao_tui_quan"
  - "cho_tay_vao_tui_ao"
  - "cho_tay_vao_tui_deo_tren_nguoi"
  - "cho_tay_vao_tui_cam_tren_tay"
  - "cho_tay_vao_gio_xe_hang"
  - "cho_tay_vao_ke"
  - "tay_cam_san_pham"
  - "tay_khong_cam_san_pham"

# Dữ liệu tập Train: Mỗi class là một list các file .txt chứa đường dẫn ảnh
train_data:
  cho_tay_vao_tui_quan: 
    - /home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_quan/train--min4k--max5k.txt
    - /home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8/cho_tay_vao_tui_quan/train--1.5k.txt
  cho_tay_vao_tui_ao: 
    - /home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_ao/train--min4k--max5k.txt
    - /home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8/cho_tay_vao_tui_ao/train--1.5k.txt
  cho_tay_vao_tui_deo_tren_nguoi: 
    - /home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_deo_tren_nguoi/train--min4k--max5k.txt
    - /home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8/cho_tay_vao_tui_deo_tren_nguoi/train--1.5k.txt
  cho_tay_vao_tui_cam_tren_tay: 
    - /home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_cam_tren_tay/train--min4k--max5k.txt
    - /home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8/cho_tay_vao_tui_cam_tren_tay/train--1.5k.txt
  cho_tay_vao_gio_xe_hang: ["/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_gio_xe_hang/train--min4k--max5k.txt"]
  cho_tay_vao_ke: ["/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_ke/train--min4k--max5k.txt"]
  tay_cam_san_pham: ["/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/tay_cam_san_pham/train--min4k--max5k.txt"]
  tay_khong_cam_san_pham: ["/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/tay_khong_cam_san_pham/train--min4k--max5k.txt"]

# Dữ liệu tập Val/Test
val_data:
  cho_tay_vao_tui_quan: ["/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_quan/val--min4k--max5k.txt"]
  cho_tay_vao_tui_ao: ["/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_ao/val--min4k--max5k.txt"]
  cho_tay_vao_tui_deo_tren_nguoi: ["/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_deo_tren_nguoi/val--min4k--max5k.txt"]
  cho_tay_vao_tui_cam_tren_tay: ["/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_tui_cam_tren_tay/val--min4k--max5k.txt"]
  cho_tay_vao_gio_xe_hang: ["/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_gio_xe_hang/val--min4k--max5k.txt"]
  cho_tay_vao_ke: ["/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/cho_tay_vao_ke/val--min4k--max5k.txt"]
  tay_cam_san_pham: ["/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/tay_cam_san_pham/val--min4k--max5k.txt"]
  tay_khong_cam_san_pham: ["/home/laptq/laptq-fs26-shoplifting-detection/outputs/train_data/classify_rgb/my_format/labels_actions--cluster-CNN-8--cut-l4/tay_khong_cam_san_pham/val--min4k--max5k.txt"]

# Tham số Training
epochs: 100
batch_size: 64
lr: 1e-4
weight_decay: 0.0005
patience: 20
num_workers: 4
precision: 32 # Có thể dùng 16 hoặc 32

accelerator: "gpu" # "cpu", "gpu"
devices: [2, 3, 4, 5] # "auto", 0, 1, ...